name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master

        with:

          host:
            ${{ secrets.EC2_HOST }}

          username:
            ${{ secrets.EC2_USERNAME }}

          key:
            ${{ secrets.EC2_SSH_KEY }}

          script: |

            cd ai-expense-analyzer

            git pull origin main

            sudo docker stop ai-expense-app || true

            sudo docker rm ai-expense-app || true

            sudo docker build -t ai-expense-analyzer .

            sudo docker run -d \
              -p 8000:8000 \
              --env-file .env \
              --name ai-expense-app \
              ai-expense-analyzer